INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (1, '976 Atwood Hill', 'Johor Bahru', '80600', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (2, '398 Bluestem Court', 'Alor Star', '06250', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (3, '77777 Bartelt Parkway', 'Kota Bharu', '15630', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (4, '0499 Londonderry Street', 'Melaka', '75648', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (5, '007 Daystar Alley', 'Kuala Pilah', '72507', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (6, '313 Pierstorff Center', 'Kuala Terengganu', '20710', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (7, '74536 Scofield Road', 'Ipoh', '30200', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (8, '8 Sutherland Terrace', 'Kangar', '01578', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (9, '600 Clyde Gallagher Hill', 'Pulau Pinang', '10450', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (10, '6814 Welch Junction', 'Kota Kinabalu', '88906', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (11, '30260 Forster Parkway', 'Kuching', '93520', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (12, '625 Grover Crossing', 'Petaling Jaya', '46964', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (13, '0 Raven Point', 'Kuala Lumpur', '50802', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (14, '48158 Elka Pass', 'Petaling Jaya', '46547', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (15, '1 Harbort Place', 'Kota Kinabalu', '88788', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (16, '76 Northfield Terrace', 'Petaling Jaya', '46547', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (17, '70436 Melody Crossing', 'Kota Kinabalu', '88540', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (18, '435 Melby Parkway', 'Kuala Lumpur', '57990', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (19, '46 Algoma Plaza', 'Kuala Lumpur', '50634', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (20, '3400 Londonderry Junction', 'Ipoh', '30532', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (21, '01 Knutson Way', 'Kota Kinabalu', '88906', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (22, '3 Buena Vista Avenue', 'Kuala Lumpur', '50634', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (23, '249 Pawling Drive', 'Kuala Terengganu', '21009', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (24, '7 Debs Hill', 'Lahad Datu', '91117', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (25, '8772 Springs Hill', 'Kuala Lumpur', '55100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (26, '8791 Russell Center', 'Kuala Terengganu', '20608', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (27, '55 Bayside Place', 'Kota Bharu', '15500', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (28, '60179 Macpherson Street', 'Melaka', '75518', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (29, '4440 Daystar Pass', 'Butterworth', '12700', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (30, '947 Forest Drive', 'Kangar', '01578', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (31, '29 Dovetail Alley', 'Klang', '41720', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (32, '49 Bluejay Road', 'Kangar', '01673', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (33, '250 Annamark Terrace', 'Kuala Terengganu', '20551', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (34, '30782 Maple Wood Place', 'Kuala Lumpur', '59800', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (35, '2 Badeau Terrace', 'Kuala Lumpur', '57990', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (36, '95 Old Shore Way', 'Klang', '41918', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (37, '61467 Forest Dale Terrace', 'Kuala Terengganu', '20668', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (38, '708 Anderson Court', 'Ipoh', '30592', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (39, '0 Transport Alley', 'Kuching', '93558', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (40, '0 Fordem Hill', 'Petaling Jaya', '46675', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (41, '10 Alpine Terrace', 'Kota Kinabalu', '88540', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (42, '565 Sunnyside Pass', 'Alor Setar', '05590', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (43, '47894 Clove Circle', 'Kuala Terengganu', '20630', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (44, '088 Sutherland Junction', 'Kota Kinabalu', '88758', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (45, '026 Beilfuss Pass', 'Melaka', '75518', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (46, '69292 Wayridge Place', 'Kota Kinabalu', '88861', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (47, '6063 Armistice Circle', 'Sandakan', '90705', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (48, '0 Maple Way', 'Kota Kinabalu', '88788', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (49, '6 Sullivan Road', 'Alor Star', '06250', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (50, '7109 Westerfield Avenue', 'Pulau Pinang', '10662', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (51, '91046 Canary Way', 'Kota Bharu', '15604', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (52, '7 Maryland Place', 'Kangar', '01630', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (53, '82984 Lerdahl Center', 'Petaling Jaya', '46791', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (54, '197 Almo Circle', 'Tawau', '91020', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (55, '48 Vidon Court', 'Kota Kinabalu', '88906', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (56, '2 Carioca Center', 'Kota Kinabalu', '88817', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (57, '96 Gerald Point', 'Lahad Datu', '91117', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (58, '004 Alpine Point', 'Kota Kinabalu', '88847', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (59, '52710 Rockefeller Way', 'Kuching', '93150', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (60, '33872 Loomis Park', 'Nusajaya', '79518', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (61, '1 Mayer Point', 'Kuala Terengganu', '20630', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (62, '2 Namekagon Crossing', 'Johor Bahru', '80600', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (63, '23 Oakridge Point', 'Melaka', '75200', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (64, '50047 Thompson Lane', 'Ipoh', '31407', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (65, '2254 Gina Center', 'Alor Star', '06250', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (66, '940 Vidon Parkway', 'Kuala Terengganu', '20520', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (67, '323 Grim Place', 'Kota Kinabalu', '88837', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (68, '75737 Clove Way', 'Ipoh', '30674', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (69, '09427 Carey Pass', 'Butterworth', '12700', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (70, '0656 Independence Parkway', 'Alor Setar', '05622', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (71, '55983 Bultman Street', 'Kuching', '93762', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (72, '76 Vernon Junction', 'Kota Kinabalu', '88610', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (73, '50369 New Castle Way', 'Butterworth', '12700', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (74, '9 Jay Hill', 'Alor Setar', '05552', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (75, '81401 Dapin Circle', 'Kuching', '93590', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (76, '82975 Lillian Road', 'Pulau Pinang', '10512', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (77, '4 Eastlawn Center', 'Seremban', '70536', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (78, '6 Lerdahl Drive', 'Kota Kinabalu', '88837', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (79, '0 Dryden Crossing', 'Kuala Terengganu', '20520', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (80, '830 Forest Run Junction', 'Shah Alam', '40612', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (81, '9 Eggendart Court', 'Ipoh', '30648', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (82, '6644 Paget Terrace', 'Kuala Terengganu', '20520', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (83, '44 Boyd Circle', 'Tawau', '91010', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (84, '80848 Carberry Way', 'Lahad Datu', '91117', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (85, '8869 Washington Junction', 'Kota Bharu', '15500', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (86, '3502 Mitchell Terrace', 'Seremban', '70504', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (87, '41 Glendale Point', 'Kota Bharu', '15500', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (88, '9 Oak Valley Drive', 'Kota Bharu', '15740', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (89, '92 Laurel Plaza', 'Kota Kinabalu', '88512', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (90, '03446 Derek Plaza', 'Ipoh', '30200', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (91, '21 Lakewood Center', 'Ipoh', '30200', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (92, '105 Hanson Lane', 'Ipoh', '30902', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (93, '9718 Tomscot Place', 'Melaka', '75720', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (94, '157 Moulton Lane', 'Kuala Lumpur', '55100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (95, '682 Gale Pass', 'Ipoh', '30506', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (96, '60 Buell Alley', 'Kuala Lumpur', '53100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (97, '31929 Reindahl Pass', 'Kuala Lumpur', '50566', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (98, '0640 Ruskin Alley', 'Petaling Jaya', '46781', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (99, '51 6th Center', 'Kuala Lumpur', '50546', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (100, '424 Anderson Junction', 'Klang', '41200', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (101, '8 Huxley Circle', 'Klang', '41720', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (102, '01 Forest Parkway', 'Ipoh', '30532', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (103, '47609 Knutson Hill', 'Kuching', '93722', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (104, '24269 Autumn Leaf Place', 'Petaling Jaya', '46801', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (105, '7488 Monument Hill', 'Kangar', '01606', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (106, '3446 Jenifer Road', 'Seremban', '70644', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (107, '72 Vidon Terrace', 'Kuala Lumpur', '50990', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (108, '318 Annamark Crossing', 'Kangar', '01508', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (109, '219 Veith Lane', 'Kuala Lumpur', '55928', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (110, '9 Algoma Court', 'Kangar', '01673', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (111, '6 Dunning Avenue', 'Kota Kinabalu', '88998', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (112, '7431 Jenifer Pass', 'Alor Setar', '05552', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (113, '851 Sugar Crossing', 'Kuala Terengganu', '20520', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (114, '33307 Glendale Avenue', 'Lahad Datu', '91127', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (115, '084 Holmberg Park', 'Kuala Lumpur', '55928', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (116, '55870 Farmco Terrace', 'Kota Kinabalu', '88778', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (117, '5349 Derek Street', 'Kota Kinabalu', '88592', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (118, '4 Southridge Parkway', 'Kota Kinabalu', '88592', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (119, '28128 Pearson Circle', 'Ipoh', '30674', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (120, '9407 Messerschmidt Crossing', 'Seremban', '71770', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (121, '2287 Village Green Drive', 'Ipoh', '30648', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (122, '49810 Atwood Hill', 'Alor Star', '06250', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (123, '14354 Sutherland Terrace', 'Petaling Jaya', '46801', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (124, '922 Kensington Center', 'Kota Bharu', '15630', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (125, '9 Pawling Road', 'Pulau Pinang', '10450', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (126, '89 Norway Maple Place', 'Kuala Pilah', '72507', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (127, '4948 Kensington Hill', 'Kuching', '93520', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (128, '2195 Oriole Court', 'Kuala Lumpur', '50740', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (129, '0745 David Pass', 'Kota Kinabalu', '88768', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (130, '7755 Kipling Street', 'Shah Alam', '40460', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (131, '92 Orin Trail', 'Kuching', '93558', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (132, '422 West Lane', 'Kuala Lumpur', '50634', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (133, '42063 8th Pass', 'Seremban', '70644', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (134, '1516 Lyons Park', 'Klang', '41720', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (135, '5 North Place', 'Petaling Jaya', '46964', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (136, '9708 Heath Center', 'Melaka', '75910', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (137, '6 Packers Court', 'Ipoh', '30620', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (138, '1 Annamark Alley', 'Kangar', '01606', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (139, '2 Continental Alley', 'Kota Kinabalu', '88758', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (140, '7833 Lawn Alley', 'Ipoh', '30506', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (141, '4222 Ridgeview Street', 'Pulau Pinang', '10550', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (142, '4337 Anzinger Alley', 'Pasir Mas', '17020', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (143, '69245 Maywood Road', 'Kota Kinabalu', '88807', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (144, '9 Westport Drive', 'Melaka', '75503', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (145, '35743 Pankratz Street', 'Ipoh', '30902', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (146, '2540 Graedel Alley', 'Melaka', '75503', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (147, '90638 Pawling Park', 'Johor Bahru', '80600', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (148, '64 Jana Avenue', 'Sandakan', '90716', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (149, '24241 Starling Lane', 'Kuala Terengganu', '20576', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (150, '40201 Sycamore Street', 'Kuala Terengganu', '21109', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (151, '286 Melrose Plaza', 'Nusajaya', '79632', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (152, '5 Paget Plaza', 'Seremban', '71770', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (153, '59 Jackson Park', 'Alor Setar', '05516', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (154, '2 Twin Pines Avenue', 'Shah Alam', '40542', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (155, '59 Vahlen Lane', 'Lahad Datu', '91127', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (156, '5 Portage Alley', 'Petaling Jaya', '47307', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (157, '0 Gulseth Hill', 'Shah Alam', '40706', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (158, '96070 Delaware Drive', 'Petaling Jaya', '46791', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (159, '05 Fair Oaks Junction', 'Bintulu', '97010', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (160, '0873 Transport Way', 'Kuching', '93150', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (161, '3012 Heath Court', 'Seremban', '70504', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (162, '1320 Spenser Place', 'Alor Setar', '05516', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (163, '8667 Roxbury Drive', 'Kota Kinabalu', '88564', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (164, '134 Dakota Lane', 'Kuala Terengganu', '21009', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (165, '7524 Manufacturers Drive', 'Shah Alam', '40726', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (166, '08 Towne Park', 'Kuala Terengganu', '20504', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (167, '9 Morrow Crossing', 'Sandakan', '90726', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (168, '72589 Dennis Street', 'Kuala Lumpur', '50782', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (169, '3543 Holmberg Trail', 'Kangar', '01540', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (170, '0 Pennsylvania Circle', 'Kota Kinabalu', '88758', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (171, '4676 Pennsylvania Terrace', 'Shah Alam', '40460', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (172, '56834 Clyde Gallagher Way', 'Petaling Jaya', '46791', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (173, '4 Grayhawk Drive', 'Kota Bharu', '15572', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (174, '43 Darwin Pass', 'Kuching', '93722', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (175, '53673 Village Lane', 'Johor Bahru', '81310', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (176, '30708 David Junction', 'Kuching', '93722', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (177, '03350 Sundown Lane', 'Nusajaya', '79518', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (178, '961 Pepper Wood Hill', 'Shah Alam', '40582', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (179, '104 Crest Line Center', 'Alor Setar', '05720', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (180, '627 Pine View Alley', 'Kuala Lumpur', '50990', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (181, '1767 Johnson Terrace', 'Shah Alam', '40990', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (182, '8194 Beilfuss Hill', 'Kuala Lumpur', '50902', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (183, '00 Erie Junction', 'Kuala Terengganu', '21109', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (184, '54501 Arkansas Point', 'Johor Bahru', '80600', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (185, '2721 Pierstorff Terrace', 'Kuching', '93742', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (186, '0 Thierer Road', 'Kuala Terengganu', '20710', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (187, '98725 Brickson Park Street', 'Klang', '41918', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (188, '95 Harper Parkway', 'Kota Kinabalu', '88610', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (189, '05 Clemons Junction', 'Kuching', '93590', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (190, '47961 Chive Center', 'Bachok', '16070', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (191, '898 Ludington Road', 'Kota Bharu', '15572', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (192, '163 Bluestem Drive', 'Petaling Jaya', '46791', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (193, '6 Bellgrove Lane', 'Ipoh', '31407', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (194, '21606 Springs Street', 'Kangar', '01508', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (195, '14 South Center', 'Pulau Pinang', '10582', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (196, '3448 Tony Road', 'Kota Bharu', '15517', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (197, '8476 Kipling Court', 'Petaling Jaya', '46781', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (198, '9534 Manley Crossing', 'Kuching', '93504', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (199, '215 Ilene Street', 'Seremban', '70504', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (200, '2080 Farragut Place', 'Sandakan', '90705', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (201, '8 Loomis Avenue', 'Pulau Pinang', '10550', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (202, '321 Caliangt Place', 'Kuching', '93520', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (203, '924 Derek Court', 'Kota Kinabalu', '88661', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (204, '18 Express Trail', 'Johor Bahru', '81310', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (205, '3 Cody Avenue', 'Kuala Lumpur', '50802', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (206, '3 Butternut Plaza', 'Pulau Pinang', '10840', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (207, '6076 Gina Alley', 'Melaka', '75910', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (208, '4 Knutson Street', 'Klang', '41918', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (209, '12 Onsgard Place', 'Sandakan', '90726', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (210, '6 Gina Point', 'Kuching', '93916', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (211, '992 Fallview Trail', 'Klang', '41918', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (212, '25228 Farwell Lane', 'Kuala Lumpur', '50933', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (213, '57 Farmco Crossing', 'Alor Setar', '05590', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (214, '379 Bunker Hill Parkway', 'Nusajaya', '79503', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (215, '060 Debra Avenue', 'Kuala Lumpur', '50515', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (216, '20044 Erie Point', 'Kuching', '93590', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (217, '3 Harbort Place', 'Johor Bahru', '81310', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (218, '9694 Northland Junction', 'Kota Kinabalu', '88758', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (219, '63318 Calypso Point', 'Kota Kinabalu', '88628', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (220, '406 Bellgrove Drive', 'Kota Kinabalu', '88827', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (221, '10905 Westend Alley', 'Kuala Terengganu', '20916', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (222, '54783 Sachtjen Point', 'Kota Bharu', '15517', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (223, '0 Delladonna Park', 'Nusajaya', '79503', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (224, '890 Maywood Lane', 'Alor Setar', '05590', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (225, '5 Killdeer Court', 'Kuala Terengganu', '20576', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (226, '255 Elgar Drive', 'Kota Kinabalu', '88628', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (227, '69560 Schlimgen Hill', 'Melaka', '75720', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (228, '543 Rieder Junction', 'Kuching', '93520', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (229, '35 Lotheville Park', 'Shah Alam', '40672', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (230, '1 Hallows Court', 'Alor Setar', '05720', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (231, '27 Atwood Terrace', 'Kuala Terengganu', '20630', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (232, '178 Farwell Junction', 'Alor Setar', '05460', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (233, '33 Packers Trail', 'Pulau Pinang', '10740', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (234, '462 Maple Wood Street', 'Shah Alam', '40582', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (235, '86373 Eastwood Hill', 'Kuala Lumpur', '50515', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (236, '802 Vera Parkway', 'Kuala Lumpur', '50515', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (237, '80190 Moulton Court', 'Ipoh', '30554', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (238, '3 Starling Park', 'Melaka', '75518', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (239, '5 Kenwood Center', 'Kuala Lumpur', '55908', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (240, '82 Farwell Plaza', 'Kota Kinabalu', '88661', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (241, '85 Namekagon Hill', 'Kota Kinabalu', '88817', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (242, '29 Chinook Avenue', 'Seremban', '70690', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (243, '9175 Southridge Circle', 'Kangar', '01630', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (244, '93 Sutherland Circle', 'Klang', '41918', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (245, '1758 Loftsgordon Terrace', 'Melaka', '75720', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (246, '60 Dexter Terrace', 'Kuala Terengganu', '21109', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (247, '414 Mcguire Avenue', 'Kangar', '01673', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (248, '6 Portage Point', 'Melaka', '75720', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (249, '90515 Corry Plaza', 'Kuala Lumpur', '55908', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (250, '6 Trailsway Point', 'Seremban', '71770', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (251, '89490 Graedel Plaza', 'Kuala Terengganu', '20608', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (252, '6413 Thackeray Center', 'Shah Alam', '40990', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (253, '85823 Mosinee Street', 'Alor Setar', '05590', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (254, '35041 Gale Junction', 'Seremban', '71770', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (255, '90 Bartillon Avenue', 'Ipoh', '30902', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (256, '32460 Kipling Terrace', 'Johor Bahru', '80600', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (257, '6990 Goodland Lane', 'Ipoh', '30592', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (258, '401 Lerdahl Road', 'Ipoh', '30200', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (259, '0 Dryden Park', 'Kota Kinabalu', '88758', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (260, '16761 Wayridge Street', 'Kuala Lumpur', '50740', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (261, '9427 Jenifer Park', 'Ipoh', '30648', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (262, '81 Dottie Trail', 'Alor Setar', '05552', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (263, '2 7th Place', 'Bachok', '16070', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (264, '10009 Chive Circle', 'Petaling Jaya', '46781', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (265, '7 Norway Maple Way', 'Alor Setar', '05590', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (266, '7 Starling Hill', 'Kota Bharu', '15670', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (267, '71117 Moose Park', 'Kuching', '93762', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (268, '014 Myrtle Point', 'Bachok', '16070', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (269, '56100 Forest Dale Drive', 'Kota Kinabalu', '88778', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (270, '95929 Ridge Oak Court', 'Kuala Lumpur', '50782', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (271, '42 Forest Drive', 'Kangar', '01508', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (272, '4986 Lindbergh Junction', 'Melaka', '75648', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (273, '42119 Briar Crest Court', 'Kuala Lumpur', '50740', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (274, '13 Di Loreto Junction', 'Kota Kinabalu', '88827', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (275, '1 Nancy Place', 'Kota Kinabalu', '88592', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (276, '1006 Anzinger Plaza', 'Pulau Pinang', '10582', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (277, '0801 Sachtjen Center', 'Melaka', '75503', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (278, '0848 Miller Place', 'Alor Setar', '05622', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (279, '2738 Manitowish Trail', 'Alor Setar', '05720', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (280, '4 Surrey Circle', 'Butterworth', '13800', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (281, '94 Kings Drive', 'Pulau Pinang', '10662', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (282, '5 Havey Hill', 'Tawau', '91030', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (283, '97 Nevada Parkway', 'Pulau Pinang', '10550', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (284, '1847 Roth Trail', 'Kota Kinabalu', '88628', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (285, '01 Elmside Alley', 'Kuala Terengganu', '20668', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (286, '03 Logan Court', 'Alor Setar', '05460', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (287, '219 Glacier Hill Hill', 'Kota Kinabalu', '88564', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (288, '724 Continental Junction', 'Kuala Terengganu', '20668', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (289, '225 Pennsylvania Road', 'Johor Bahru', '80560', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (290, '46204 Declaration Place', 'Kuching', '93558', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (291, '9 Dovetail Trail', 'Kuala Terengganu', '21009', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (292, '84162 Eggendart Point', 'Nusajaya', '79632', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (293, '011 Summit Point', 'Kota Bharu', '15604', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (294, '3701 Maple Wood Place', 'Shah Alam', '40612', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (295, '8 Manley Lane', 'Kuala Lumpur', '50592', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (296, '26 Corben Crossing', 'Kuala Lumpur', '50490', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (297, '7 Jenna Way', 'Kota Bharu', '15500', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (298, '372 Hollow Ridge Place', 'Butterworth', '12700', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (299, '75 Memorial Court', 'Kota Kinabalu', '88540', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (300, '4228 La Follette Pass', 'Kota Bharu', '15500', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (301, '55688 Comanche Circle', 'Kuala Lumpur', '55908', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (302, '74358 Scott Junction', 'Kuching', '93612', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (303, '565 Pankratz Crossing', 'Kuching', '93762', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (304, '286 Westend Lane', 'Kuching', '93702', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (305, '32846 Magdeline Road', 'Petaling Jaya', '47307', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (306, '550 Dunning Park', 'Kuala Lumpur', '50923', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (307, '09 Cherokee Road', 'Kuala Lumpur', '59800', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (308, '0 Grayhawk Lane', 'Kuala Lumpur', '50902', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (309, '100 Transport Point', 'Klang', '41918', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (310, '8883 Meadow Ridge Avenue', 'Alor Setar', '05460', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (311, '5408 Victoria Street', 'Kuala Lumpur', '50672', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (312, '0 Prairieview Parkway', 'Alor Setar', '05552', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (313, '385 Ridge Oak Terrace', 'Kuala Lumpur', '50592', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (314, '30 Michigan Trail', 'Rawang', '48100', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (315, '61093 Toban Avenue', 'Johor Bahru', '80560', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (316, '64 Waywood Terrace', 'Kota Kinabalu', '88906', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (317, '5324 Golf Lane', 'Shah Alam', '40582', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (318, '4217 Myrtle Alley', 'Shah Alam', '40672', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (319, '170 Anthes Street', 'Lahad Datu', '91117', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (320, '2 Caliangt Hill', 'Kuala Pilah', '72507', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (321, '6632 Myrtle Court', 'Lahad Datu', '91117', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (322, '93 Fuller Avenue', 'Kuala Terengganu', '20504', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (323, '0218 Packers Place', 'Kuala Terengganu', '20608', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (324, '82615 Coleman Trail', 'Kuala Lumpur', '50592', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (325, '628 Blue Bill Park Street', 'Kota Kinabalu', '88592', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (326, '71472 Graedel Hill', 'Kota Kinabalu', '88661', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (327, '21073 Dunning Drive', 'Kuching', '93520', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (328, '68 Carberry Pass', 'Pulau Pinang', '10840', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (329, '282 Muir Circle', 'Bintulu', '97010', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (330, '6 Tomscot Way', 'Tawau', '91010', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (331, '9637 Victoria Center', 'Pulau Pinang', '10612', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (332, '17 Center Road', 'Pasir Mas', '17020', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (333, '2773 Del Sol Way', 'Kangar', '01508', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (334, '1335 Melvin Trail', 'Shah Alam', '40706', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (335, '920 Welch Court', 'Klang', '41918', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (336, '81408 High Crossing Trail', 'Kuala Terengganu', '20710', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (337, '684 Knutson Court', 'Kota Kinabalu', '88906', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (338, '33 Superior Crossing', 'Kuala Lumpur', '50515', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (339, '915 Huxley Crossing', 'Butterworth', '12700', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (340, '42 Corry Way', 'Pasir Mas', '17020', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (341, '876 Dennis Hill', 'Kuala Terengganu', '20520', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (342, '2592 Kipling Hill', 'Kuala Terengganu', '20608', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (343, '81113 Messerschmidt Place', 'Kuala Terengganu', '20551', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (344, '2508 Waubesa Avenue', 'Alor Setar', '05460', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (345, '68893 Alpine Circle', 'Kota Kinabalu', '88906', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (346, '7 American Ash Terrace', 'Seremban', '70536', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (347, '5192 Fairview Hill', 'Kuala Terengganu', '20576', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (348, '3550 Carpenter Trail', 'Petaling Jaya', '46781', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (349, '1 American Ash Avenue', 'Kuala Lumpur', '59800', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (350, '5 Lillian Park', 'Kuala Terengganu', '20520', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (351, '64793 Menomonie Avenue', 'Seremban', '71770', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (352, '2 Lawn Avenue', 'Kuala Lumpur', '59800', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (353, '6733 Vermont Center', 'Kota Kinabalu', '88817', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (354, '78 Katie Trail', 'Petaling Jaya', '46791', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (355, '85034 Thackeray Alley', 'Kuala Lumpur', '50762', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (356, '257 Basil Place', 'Kuala Lumpur', '50634', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (357, '17 Badeau Court', 'Kota Kinabalu', '88661', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (358, '912 Bluestem Crossing', 'Kota Kinabalu', '88837', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (359, '4 Cordelia Pass', 'Ipoh', '30592', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (360, '646 Westridge Place', 'Kuala Lumpur', '50782', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (361, '37 Oriole Place', 'Kuala Terengganu', '20551', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (362, '361 Merchant Park', 'Kuala Lumpur', '55908', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (363, '307 Mifflin Crossing', 'Kota Kinabalu', '88400', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (364, '38935 Golden Leaf Court', 'Kota Bharu', '15540', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (365, '441 Stone Corner Place', 'Kuala Lumpur', '50490', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (366, '7357 La Follette Point', 'Alor Setar', '05516', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (367, '21 Hoard Avenue', 'Kangar', '01540', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (368, '72 Walton Lane', 'Taiping', '34010', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (369, '88 Macpherson Road', 'Kuala Lumpur', '50546', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (370, '03857 Everett Plaza', 'Nusajaya', '79575', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (371, '2680 Emmet Place', 'Johor Bahru', '80600', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (372, '14 Pierstorff Pass', 'Alor Setar', '05720', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (373, '32131 Dwight Place', 'Kota Kinabalu', '88788', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (374, '80 Harbort Trail', 'Kuala Terengganu', '20630', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (375, '2 Crest Line Drive', 'Alor Setar', '05622', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (376, '29 Mosinee Drive', 'Kota Kinabalu', '88628', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (377, '183 Charing Cross Lane', 'Kota Kinabalu', '88758', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (378, '5147 Donald Point', 'Kota Bharu', '15630', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (379, '750 Rusk Avenue', 'Pulau Pinang', '10840', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (380, '82 Manitowish Parkway', 'Kota Bharu', '15572', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (381, '2 Johnson Road', 'Alor Setar', '05672', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (382, '7324 Roxbury Drive', 'Tawau', '91010', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (383, '5 6th Avenue', 'Kota Bharu', '15630', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (384, '94 Randy Street', 'Petaling Jaya', '46675', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (385, '6 Grasskamp Street', 'Kuching', '93558', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (386, '85 Maryland Court', 'Kuala Terengganu', '20504', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (387, '9133 Hanover Center', 'Kota Bharu', '15740', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (388, '55 Florence Terrace', 'Kota Bharu', '15500', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (389, '376 Bultman Crossing', 'Kuching', '93520', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (390, '06221 Huxley Crossing', 'Ipoh', '30902', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (391, '30555 Merchant Pass', 'Kota Kinabalu', '88512', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (392, '935 Sachtjen Road', 'Alor Setar', '05516', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (393, '265 Welch Place', 'Melaka', '75586', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (394, '20745 Talisman Plaza', 'Alor Star', '06250', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (395, '4336 Leroy Drive', 'Pulau Pinang', '10512', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (396, '9 Chinook Avenue', 'Petaling Jaya', '46781', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (397, '46 Armistice Park', 'Kuala Lumpur', '55100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (398, '6457 Golf Course Court', 'Kota Bharu', '15740', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (399, '8509 Anhalt Plaza', 'Kuala Lumpur', '50490', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (400, '982 Hagan Hill', 'Kuching', '93722', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (401, '70 Killdeer Drive', 'Melaka', '75610', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (402, '37989 Merchant Lane', 'Kuching', '93520', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (403, '70 Crest Line Terrace', 'Kuala Lumpur', '59800', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (404, '99320 Banding Avenue', 'Kuala Pilah', '72507', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (405, '52 Corscot Lane', 'Kuching', '93504', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (406, '80168 Harper Way', 'Kota Kinabalu', '88758', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (407, '50 Hayes Road', 'Kuala Terengganu', '20916', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (408, '744 Eliot Court', 'Seremban', '70572', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (409, '42472 Rockefeller Junction', 'Tawau', '91010', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (410, '71079 North Junction', 'Kota Kinabalu', '88592', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (411, '440 Union Park', 'Kuala Lumpur', '50566', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (412, '20 Calypso Crossing', 'Kuala Lumpur', '50546', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (413, '86533 Vidon Pass', 'Kuala Terengganu', '20710', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (414, '3791 Westridge Alley', 'Pulau Pinang', '10662', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (415, '65 Mallory Terrace', 'Kuala Lumpur', '50592', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (416, '91749 Oriole Alley', 'Shah Alam', '40542', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (417, '77 Farmco Road', 'Kota Kinabalu', '88998', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (418, '2 Lyons Terrace', 'Kuala Lumpur', '50592', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (419, '55627 Merrick Hill', 'Kuala Lumpur', '50490', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (420, '0426 Lighthouse Bay Avenue', 'Kuala Lumpur', '50802', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (421, '50279 Browning Place', 'Kota Kinabalu', '88872', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (422, '8 Dovetail Alley', 'Kuala Terengganu', '20916', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (423, '4 Northland Way', 'Pulau Pinang', '10740', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (424, '2 Delladonna Court', 'Lahad Datu', '91117', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (425, '56 Trailsway Parkway', 'Kota Kinabalu', '88788', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (426, '8 Jenna Street', 'Kuala Lumpur', '50990', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (427, '7547 Trailsway Parkway', 'Kota Kinabalu', '88592', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (428, '910 John Wall Parkway', 'Rawang', '48100', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (429, '83655 Nobel Park', 'Kuala Lumpur', '55100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (430, '22397 Magdeline Court', 'Seremban', '70604', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (431, '22547 Dovetail Park', 'Kuala Lumpur', '50515', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (432, '452 Anhalt Park', 'Pulau Pinang', '10662', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (433, '3449 7th Way', 'Kuching', '93742', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (434, '29 Mariners Cove Lane', 'Kota Kinabalu', '88998', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (435, '30465 Reinke Circle', 'Kangar', '01508', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (436, '333 Marcy Pass', 'Kuala Terengganu', '20668', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (437, '13 Del Sol Point', 'Petaling Jaya', '46781', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (438, '93 Dahle Street', 'Kuala Lumpur', '50720', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (439, '3 Sullivan Pass', 'Pulau Pinang', '10512', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (440, '8436 Rutledge Avenue', 'Kota Kinabalu', '88758', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (441, '34 Moose Place', 'Melaka', '75552', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (442, '1 Troy Drive', 'Petaling Jaya', '46781', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (443, '590 Grayhawk Junction', 'Kuala Terengganu', '20630', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (444, '8 Eastwood Center', 'Kuching', '93658', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (445, '72048 Luster Place', 'Seremban', '70536', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (446, '93 Lunder Trail', 'Kota Kinabalu', '88610', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (447, '2587 Hintze Road', 'Kuala Terengganu', '20668', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (448, '2378 Farmco Pass', 'Kota Kinabalu', '88778', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (449, '3 Hermina Center', 'Seremban', '70536', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (450, '5 Monterey Center', 'Kota Kinabalu', '88564', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (451, '38 Erie Lane', 'Kuala Lumpur', '50672', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (452, '9 Coleman Park', 'Kuala Lumpur', '55100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (453, '99046 Northview Road', 'Kota Kinabalu', '88807', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (454, '634 Eagan Place', 'Kuala Lumpur', '53100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (455, '00 Dawn Circle', 'Pulau Pinang', '10740', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (456, '6631 Eastwood Court', 'Shah Alam', '40582', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (457, '3 Parkside Street', 'Rawang', '48100', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (458, '477 Fallview Plaza', 'Kuala Terengganu', '20551', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (459, '90798 Cascade Plaza', 'Kuala Lumpur', '55100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (460, '56666 Lighthouse Bay Parkway', 'Sandakan', '90705', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (461, '534 Karstens Trail', 'Kangar', '01673', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (462, '83 Michigan Court', 'Alor Setar', '05552', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (463, '989 Luster Park', 'Taiping', '34010', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (464, '7 Talmadge Plaza', 'Shah Alam', '40672', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (465, '34 Summit Junction', 'Bintulu', '97010', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (466, '21973 Blaine Place', 'Shah Alam', '40460', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (467, '797 Crowley Trail', 'Kuala Lumpur', '50943', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (468, '697 Lake View Parkway', 'Kangar', '01578', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (469, '305 Jenna Place', 'Kuala Lumpur', '50546', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (470, '2824 Shopko Point', 'Kota Bharu', '15630', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (471, '224 Independence Center', 'Kota Kinabalu', '88788', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (472, '727 Oak Crossing', 'Pulau Pinang', '10550', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (473, '7293 Golf View Avenue', 'Kuala Lumpur', '50782', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (474, '5 Artisan Drive', 'Ipoh', '30592', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (475, '51 Dovetail Trail', 'Kuala Lumpur', '50720', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (476, '07 Ridge Oak Avenue', 'Kuala Terengganu', '20608', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (477, '944 Heath Road', 'Kangar', '01508', 'Perlis', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (478, '462 Springs Junction', 'Kuala Lumpur', '50515', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (479, '277 John Wall Lane', 'Petaling Jaya', '46801', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (480, '52955 Bellgrove Way', 'Kuching', '93722', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (481, '741 Manley Crossing', 'Kuala Lumpur', '55100', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (482, '7 Moland Park', 'Kota Bharu', '15517', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (483, '8299 Darwin Circle', 'Shah Alam', '40460', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (484, '95468 Mosinee Plaza', 'Johor Bahru', '80600', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (485, '78347 Oriole Court', 'Tawau', '91010', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (486, '9 Hooker Pass', 'Kuching', '93916', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (487, '7 Pawling Drive', 'Kuala Lumpur', '50566', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (488, '49 Melrose Place', 'Rawang', '48100', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (489, '8 Forster Court', 'Kota Kinabalu', '88512', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (490, '56134 Lighthouse Bay Pass', 'Melaka', '75503', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (491, '800 Becker Hill', 'Alor Setar', '05516', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (492, '65 Longview Lane', 'Kuala Lumpur', '55908', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (493, '386 Sage Place', 'Kuala Lumpur', '57990', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (494, '4 Lindbergh Way', 'Melaka', '75610', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (495, '8 Linden Point', 'Kuala Terengganu', '20630', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (496, '198 Esker Drive', 'Kuala Terengganu', '20520', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (497, '7 Rieder Point', 'Kuala Lumpur', '50782', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (498, '56237 Alpine Avenue', 'Kota Bharu', '15517', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (499, '6 Porter Place', 'Ipoh', '30592', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) values (500, '96 Vernon Way', 'Shah Alam', '40706', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (501, '1124 Evergreen Terrace', 'Kuala Lumpur', '50480', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (502, '78 Banyan Drive', 'George Town', '10200', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (503, '563 Sunrise Boulevard', 'Petaling Jaya', '46050', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (504, '93 Magnolia Crescent', 'Johor Bahru', '80000', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (505, '245 Cedar Road', 'Seremban', '70300', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (506, '317 Willow Lane', 'Ipoh', '30050', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (507, '429 Aspen Way', 'Kota Kinabalu', '88000', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (508, '1312 Palm Street', 'Kuching', '93100', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (509, '57 Maple Avenue', 'Kuala Terengganu', '21010', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (510, '884 Birch Parkway', 'Alor Setar', '05150', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (511, '220 Redwood Court', 'Kuala Lumpur', '50250', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (512, '16 Oak Street', 'Melaka', '75000', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (513, '712 Pine Ridge', 'Bentong', '28700', 'Pahang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (514, '389 Cypress Road', 'Tawau', '91000', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (515, '145 Hemlock Drive', 'Sandakan', '90000', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (516, '664 Poplar Lane', 'Kota Bharu', '15000', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (517, '58 Elm Street', 'Labuan', '87000', 'Labuan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (518, '937 Sycamore Avenue', 'Kuala Lumpur', '55000', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (519, '304 Juniper Way', 'Ipoh', '31500', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (520, '881 Cherry Court', 'Seremban', '70400', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (521, '210 Dogwood Lane', 'Shah Alam', '40100', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (522, '19 Fir Street', 'George Town', '10300', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (523, '746 Alder Drive', 'Johor Bahru', '80200', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (524, '321 Palm Court', 'Melaka', '75200', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (525, '412 Acacia Road', 'Kuah', '07000', 'Kedah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (526, '57 Laurel Avenue', 'Kota Kinabalu', '88300', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (527, '698 Spruce Street', 'Kuching', '93250', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (528, '825 Banyan Boulevard', 'Seremban', '70500', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (529, '143 Elm Ridge', 'Kuala Terengganu', '21100', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (530, '962 Aspen Drive', 'Petaling Jaya', '47301', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (531, '37 Pine Street', 'Ipoh', '30600', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (532, '214 Oak Avenue', 'George Town', '10150', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (533, '579 Redwood Road', 'Shah Alam', '40200', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (534, '688 Cedar Court', 'Johor Bahru', '80300', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (535, '150 Cypress Lane', 'Kuala Lumpur', '50550', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (536, '870 Laurel Crescent', 'Melaka', '75400', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (537, '295 Fir Boulevard', 'Kuching', '93400', 'Sarawak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (538, '413 Juniper Avenue', 'Labuan', '87100', 'Labuan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (539, '501 Dogwood Drive', 'Kota Bharu', '15200', 'Kelantan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (540, '762 Birch Lane', 'Kota Kinabalu', '88450', 'Sabah', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (541, '319 Magnolia Street', 'Kuala Terengganu', '21200', 'Terengganu', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (542, '44 Spruce Avenue', 'Ipoh', '30700', 'Perak', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (543, '558 Hemlock Road', 'Johor Bahru', '80400', 'Johor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (544, '821 Poplar Court', 'George Town', '10120', 'Pulau Pinang', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (545, '129 Cedar Lane', 'Petaling Jaya', '46610', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (546, '644 Pine Crescent', 'Seremban', '70600', 'Negeri Sembilan', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (547, '237 Oak Ridge', 'Shah Alam', '40300', 'Selangor', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (548, '398 Fir Court', 'Melaka', '75600', 'Melaka', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (549, '72 Elm Boulevard', 'Kuala Lumpur', '50600', 'Kuala Lumpur', 'Malaysia');
INSERT INTO Address (AddressID, Street, City, PostalCode, State, Country) VALUES (550, '905 Redwood Lane', 'Kota Kinabalu', '88500', 'Sabah', 'Malaysia');
