INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (1, 'Darin', 'Baggarley', 'M', 'Darin Baggarley is a celebrated crime novelist known for his gripping urban thrillers.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (2, 'Geno', 'Apthorpe', 'M', 'Geno Apthorpe writes visionary science fiction exploring futuristic societies and AI ethics.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (3, 'Appolonia', 'Myott', 'F', 'Appolonia Myott crafts heartwarming children’s books about friendship and discovery.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (4, 'Tito', 'Spuner', 'M', 'Tito Spuner is an award‑winning travel writer chronicling off‑the‑beaten‑path adventures.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (5, 'Lemuel', 'Sacco', 'M', 'Lemuel Sacco researches and writes in‑depth historical nonfiction on medieval Europe.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (6, 'Latrena', 'Killingsworth', 'F', 'Latrena Killingsworth is a poet whose lyrical verses explore themes of love and loss.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (7, 'Evanne', 'Pogosian', 'F', 'Evanne Pogosian works as a literary critic and essayist for major cultural magazines.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (8, 'Teresina', 'Wayper', 'F', 'Teresina Wayper pens sweeping romance novels set in sun‑drenched countrysides.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (9, 'Nolly', 'Boyne', 'M', 'Nolly Boyne is a graphic novelist combining noir aesthetics with social commentary.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (10, 'Wallie', 'Jee', 'M', 'Wallie Jee writes screenplays for independent films and TV dramas.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (11, 'Meghan', 'Wilding', 'F', 'Meghan Wilding is a fantasy author weaving epic tales of magic and heroism.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (12, 'Jeana', 'Thake', 'F', 'Jeana Thake publishes acclaimed short story collections on everyday mysteries.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (13, 'Lenka', 'Portman', 'F', 'Lenka Portman is a modern dramatist whose plays examine family dynamics.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (14, 'Brenden', 'Roseby', 'M', 'Brenden Roseby covers international sports as a seasoned journalist.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (15, 'Codie', 'Vedeniktov', 'M', 'Codie Vedeniktov runs a popular tech blog focusing on programming tutorials.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (16, 'Esma', 'Leban', 'F', 'Esma Leban writes self-help books empowering readers to build resilience.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (17, 'Bondy', 'Pegrum', 'M', 'Bondy Pegrum has reported from conflict zones as a frontline war correspondent.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (18, 'Gavin', 'Darragh', 'M', 'Gavin Darragh specializes in writing biographies of influential leaders.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (19, 'Delcina', 'Nund', 'F', 'Delcina Nund is an environmental campaigner and nature writer.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (20, 'Marcelline', 'Richens', 'F', 'Marcelline Richens critiques cuisines worldwide as a respected food critic.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (21, 'Jeffrey', 'Boydell', 'M', 'Jeffrey Boydell analyzes political trends as a seasoned commentator.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (22, 'Mikey', 'Benoy', 'M', 'Mikey Benoy pens humor columns that poke fun at modern life.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (23, 'Damita', 'Slight', 'F', 'Damita Slight covers the music industry with artist interviews and album reviews.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (24, 'Alisun', 'Bushen', 'F', 'Alisun Bushen is an academic researcher publishing on cognitive psychology.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (25, 'Cordell', 'Gatland', 'M', 'Cordell Gatland writes thought-provoking nonfiction essays on culture.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (26, 'Ransom', 'Paton', 'M', 'Ransom Paton crafts high-octane adventure novels set in exotic locales.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (27, 'Tam', 'Worpole', 'M', 'Tam Worpole explores mystical fiction inspired by ancient legends.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (28, 'Malanie', 'Collcott', 'F', 'Malanie Collcott blends romance and travel memoir in her bestselling books.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (29, 'Edithe', 'Costello', 'F', 'Edithe Costello authors practical parenting guides for new families.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (30, 'Lucian', 'Buckle', 'M', 'Lucian Buckle writes engaging philosophy books for general audiences.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (31, 'Erna', 'Thoma', 'F', 'Erna Thoma is an art historian specializing in Renaissance masterpieces.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (32, 'Luciano', 'Snodden', 'M', 'Luciano Snodden popularizes complex science through accessible books.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (33, 'Berni', 'Overill', 'F', 'Berni Overill advises businesses as a bestselling strategist author.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (34, 'Brita', 'De Avenell', 'F', 'Brita De Avenell publishes research-driven works on climate change.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (35, 'Nat', 'Finnemore', 'M', 'Nat Finnemore writes scripts for award-winning documentaries.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (36, 'Tybalt', 'Gronav', 'M', 'Tybalt Gronav translates classical literature into modern vernacular.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (37, 'Penelopa', 'Dodds', 'F', 'Penelopa Dodds pens feminist essays on gender and society.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (38, 'Cloe', 'Foltin', 'F', 'Cloe Foltin writes adventurous children’s novels featuring young heroines.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (39, 'Aile', 'Message', 'F', 'Aile Message is a bestselling mystery novelist known for twist endings.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (40, 'Ernst', 'Gheeraert', 'M', 'Ernst Gheeraert writes psychological thrillers that keep readers on edge.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (41, 'Jerri', 'Mc Curlye', 'M', 'Jerri Mc Curlye published a popular autobiography about his musical journey.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (42, 'Pippo', 'Peert', 'M', 'Pippo Peert writes cultural anthropology books on tribal societies.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (43, 'Gwen', 'Trusler', 'F', 'Gwen Trusler publishes enchanting fantasy short stories.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (44, 'Ody', 'Britzius', 'M', 'Ody Britzius researches paranormal phenomena in non-fiction works.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (45, 'Olin', 'Smiz', 'M', 'Olin Smiz pens nautical fiction inspired by ocean voyages.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (46, 'Mark', 'Greeve', 'M', 'Mark Greeve blends travel photography with memoir in his books.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (47, 'Lynde', 'Bouller', 'F', 'Lynde Bouller writes romantic poetry capturing the beauty of nature.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (48, 'Leupold', 'Jankin', 'M', 'Leupold Jankin is a genealogist documenting family histories.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (49, 'Currey', 'Webborn', 'M', 'Currey Webborn writes dystopian young adult novels.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (50, 'Tallia', 'Laffan', 'F', 'Tallia Laffan authors health and wellness guides focusing on holistic care.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (51, 'Normie', 'Pountain', 'M', 'Normie Pountain writes language-learning books for beginners.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (52, 'Blondelle', 'Pittet', 'F', 'Blondelle Pittet covers the world of fashion as an industry journalist.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (53, 'Dmitri', 'Hardwell', 'M', 'Dmitri Hardwell pens political memoirs of key twentieth-century figures.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (54, 'Casey', 'Prichard', 'M', 'Casey Prichard writes practical startup guides for entrepreneurs.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (55, 'Naomi', 'Draye', 'F', 'Naomi Draye critiques contemporary art in major gallery catalogs.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (56, 'Megan', 'Catlin', 'F', 'Megan Catlin authors a popular parenting advice column.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (57, 'Christie', 'Tofanini', 'M', 'Christie Tofanini reports on major criminal cases as a crime journalist.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (58, 'Faina', 'Chapleo', 'F', 'Faina Chapleo collects and retells folk tales from around the world.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (59, 'Avigdor', 'Saby', 'M', 'Avigdor Saby writes scholarly works on comparative theology.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (60, 'Jermaine', 'Stygall', 'M', 'Jermaine Stygall pens engaging sports biographies of legendary athletes.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (61, 'Adam', 'Semour', 'M', 'Adam Semour authors comprehensive software engineering textbooks.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (62, 'Christian', 'Gilbride', 'F', 'Christian Gilbride writes on LGBTQ+ rights and personal narratives.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (63, 'Fae', 'Vedyasov', 'F', 'Fae Vedyasov is a romantic poet whose verses explore the heart’s depths.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (64, 'Sydney', 'Trevers', 'M', 'Sydney Trevers writes urban fantasy novels with strong heroines.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (65, 'Avrom', 'Elstone', 'M', 'Avrom Elstone researches religious history in detailed monographs.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (66, 'Carlin', 'Knipe', 'F', 'Carlin Knipe creates educational children’s books on science and nature.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (67, 'Lesley', 'Philott', 'F', 'Lesley Philott writes forensic science guides for true-crime enthusiasts.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (68, 'Addison', 'Lawton', 'M', 'Addison Lawton pens steamy romance novellas set in coastal towns.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (69, 'Gaby', 'Herkess', 'M', 'Gaby Herkess is a travelogue author exploring hidden corners of the globe.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (70, 'Amanda', 'Dedden', 'F', 'Amanda Dedden writes mental health advocacy books and personal essays.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (71, 'Honoria', 'Frossell', 'F', 'Honoria Frossell is a classical music historian and critic.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (72, 'Lutero', 'McKennan', 'M', 'Lutero McKennan pens gripping legal thrillers based on courtroom drama.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (73, 'Torr', 'Kinch', 'M', 'Torr Kinch writes authoritative guides on corporate finance.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (74, 'Lon', 'Grunson', 'M', 'Lon Grunson researches twentieth-century wars in scholarly volumes.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (75, 'Ashlin', 'Troillet', 'M', 'Ashlin Troillet authors contemporary young adult fiction about self-discovery.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (76, 'Mitchell', 'Grabbam', 'M', 'Mitchell Grabbam writes in-depth technical manuals for industrial machinery.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (77, 'Teena', 'Lefort', 'F', 'Teena Lefort combines landscape photography with reflective essays.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (78, 'Janessa', 'Behagg', 'F', 'Janessa Behagg authors entrepreneurship coaching books based on real cases.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (79, 'Pearline', 'Yesinov', 'F', 'Pearline Yesinov researches civil rights movements in detailed histories.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (80, 'Rudie', 'Childs', 'M', 'Rudie Childs covers the automotive industry as a leading motor journalist.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (81, 'Maximilian', 'Sockell', 'M', 'Maximilian Sockell translates world poetry into contemporary English.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (82, 'Evonne', 'Oxton', 'F', 'Evonne Oxton writes riveting true crime investigations.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (83, 'Sergeant', 'Yell', 'M', 'Sergeant Yell is a maritime historian chronicling naval battles.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (84, 'Mel', 'Demougeot', 'F', 'Mel Demougeot creates illustrated children’s fantasies about magical creatures.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (85, 'Daryle', 'McGibbon', 'M', 'Daryle McGibbon writes macroeconomic analyses for policy makers.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (86, 'Elle', 'Stickel', 'F', 'Elle Stickel critiques films in a popular online cinephile column.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (87, 'Rosaleen', 'Haker', 'F', 'Rosaleen Haker authors gardening and botany guides for enthusiasts.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (88, 'Andi', 'Hodgins', 'F', 'Andi Hodgins writes cultural travel guides focused on local customs.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (89, 'Francklyn', 'Marjanovic', 'M', 'Francklyn Marjanovic analyzes military strategy in modern conflicts.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (90, 'Inesita', 'Gaitone', 'F', 'Inesita Gaitone pens books on environmental policy and sustainability.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (91, 'Rycca', 'Martill', 'F', 'Rycca Martill writes social psychology books for a general audience.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (92, 'Bill', 'Metzke', 'M', 'Bill Metzke authors practical financial planning handbooks.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (93, 'Ced', 'Gilbey', 'M', 'Ced Gilbey covers the tech startup scene as an industry journalist.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (94, 'Urban', 'Suffe', 'M', 'Urban Suffe researches urban planning in comprehensive monographs.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (95, 'Linzy', 'Reisenberg', 'F', 'Linzy Reisenberg writes art therapy guides blending creativity and healing.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (96, 'Shalna', 'Langcaster', 'F', 'Shalna Langcaster authors deeply personal memoirs and diaries.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (97, 'Vanya', 'Sket', 'F', 'Vanya Sket writes mythological fiction inspired by global folklore.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (98, 'Berry', 'Nurdin', 'F', 'Berry Nurdin authors innovative cooking recipe collections.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (99, 'Willamina', 'Jayume', 'F', 'Willamina Jayume writes elder care advice guides for families.');
INSERT INTO Author (AuthorID, AuthorFirstName, AuthorLastName, AuthorGender, Biography) VALUES (100, 'Glori', 'Ubee', 'F', 'Glori Ubee is a poet whose nature-inspired verses evoke vivid imagery.');

