INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (1, 214, 214, 'Penguin Random House');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (2, 215, 215, 'HarperCollins');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (3, 216, 216, 'Simon & Schuster');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (4, 217, 217, 'Macmillan Publishers');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (5, 218, 218, 'Hachette Book Group');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (6, 219, 219, 'Scholastic Inc.');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (7, 220, 220, 'Oxford University Press');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (8, 221, 221, 'Cambridge University Press');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (9, 222, 222, 'Pearson Education');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (10, 223, 223, 'McGraw-Hill Education');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (11, 224, 224, 'Wiley');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (12, 225, 225, 'Elsevier');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (13, 226, 226, 'Springer Nature');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (14, 227, 227, 'Cengage Learning');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (15, 228, 228, 'DK Publishing');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (16, 229, 229, 'Bloomsbury Publishing');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (17, 230, 230, 'Faber & Faber');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (18, 231, 231, 'Pan Macmillan');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (19, 232, 232, 'Abrams Books');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (20, 233, 233, 'Chronicle Books');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (21, 234, 234, 'Little, Brown and Company');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (22, 235, 235, 'Tor Books');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (23, 236, 236, 'Routledge');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (24, 237, 237, 'Verso Books');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (25, 238, 238, 'MIT Press');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (26, 239, 239, 'Dewan Bahasa dan Pustaka (DBP)');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (27, 240, 240, 'Karangkraf');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (28, 241, 241, 'PTS Publications');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (29, 242, 242, 'ITBM');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (30, 243, 243, 'Kumpulan Media Karangkraf');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (31, 244, 244, 'Alaf 21');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (32, 245, 245, 'Buku Fixi');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (33, 246, 246, 'Lejen Press');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (34, 247, 247, 'Sasbadi Holdings');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (35, 248, 248, 'Ana Muslim');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (36, 249, 249, 'Must Read');
INSERT INTO Publisher (PublisherID, AddressID, ContactID,  PublisherName) VALUES (37, 250, 250, 'Pelangi Publishing');
