DROP TABLE Payment;
DROP TABLE Invoice;
DROP TABLE Fine;
DROP TABLE Loan;
DROP TABLE BookCopy;
DROP TABLE Book;
DROP TABLE LanguageCode;
DROP TABLE BookCategory;
DROP TABLE Category;
DROP TABLE BookAuthor;
DROP TABLE Author;
DROP TABLE Borrower;
DROP TABLE Membership;
DROP TABLE StatusCode;
DROP TABLE MembershipType;
DROP TABLE StaffShiftSchedule;
DROP TABLE ShiftType;
DROP TABLE LibraryBranch;
DROP TABLE StaffPerformanceReview;
DROP TABLE Staff;
DROP TABLE StaffRole;
DROP TABLE Publisher;
DROP TABLE Contact;
DROP TABLE Address;

@@ tableAddress.sql;
@@ tableContact.sql;
@@ tablePublisher.sql;
@@ tableStaffRole.sql;
@@ tableStaff.sql;
@@ tableStaffPerformanceReview.sql;
@@ tableLibraryBranch.sql;
@@ tableShiftType.sql;
@@ tableStaffShiftSchedule.sql;
@@ tableMembershipType.sql;
@@ tableStatusCode.sql;
@@ tableMembership.sql;
@@ tableBorrower.sql;
@@ tableAuthor.sql;
@@ tableBookAuthor.sql;
@@ tableCategory.sql;
@@ tableBookCategory.sql;
@@ tableLanguageCode.sql;
@@ tableBook.sql;
@@ tableBookCopy.sql;
@@ tableLoan.sql;
@@ tableFine.sql;
@@ tableInvoice.sql;
@@ tablePayment.sql;
