-- WARN: Pending testing
DROP TABLE MembershipCatalog CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Invoice CASCADE CONSTRAINTS;
DROP TABLE Fine CASCADE CONSTRAINTS;
DROP TABLE Loan CASCADE CONSTRAINTS;
DROP TABLE BookCopy CASCADE CONSTRAINTS;
DROP TABLE Book CASCADE CONSTRAINTS;
DROP TABLE LanguageCode CASCADE CONSTRAINTS;
DROP TABLE BookCategory CASCADE CONSTRAINTS;
DROP TABLE Category CASCADE CONSTRAINTS;
DROP TABLE BookAuthor CASCADE CONSTRAINTS;
DROP TABLE Author CASCADE CONSTRAINTS;
DROP TABLE Borrower CASCADE CONSTRAINTS;
DROP TABLE Membership CASCADE CONSTRAINTS;
DROP TABLE StatusCode CASCADE CONSTRAINTS;
DROP TABLE MembershipType CASCADE CONSTRAINTS;
DROP TABLE StaffShiftSchedule CASCADE CONSTRAINTS;
DROP TABLE Publisher CASCADE CONSTRAINTS;
DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE StaffPerformanceReview CASCADE CONSTRAINTS;
DROP TABLE StaffRole CASCADE CONSTRAINTS;
DROP TABLE ShiftType CASCADE CONSTRAINTS;
DROP TABLE LibraryBranch CASCADE CONSTRAINTS;
DROP TABLE Address CASCADE CONSTRAINTS;
DROP TABLE Contact CASCADE CONSTRAINTS;
DROP TABLE PaymentMethod CASCADE CONSTRAINTS;

@@ tableAddress.sql;
@@ tableContact.sql;
@@ tablePublisher.sql;
@@ tableStaffRole.sql;
@@ tableStaff.sql;
@@ tableStaffPerformanceReview.sql;
@@ tableLibraryBranch.sql;
@@ tableShiftType.sql;
@@ tableStaffShiftSchedule.sql;
@@ tableMembershipType.sql;
@@ tableStatusCode.sql;
@@ tableBorrower.sql;
@@ tableMembership.sql;
@@ tableAuthor.sql;
@@ tableCategory.sql;
@@ tableLanguageCode.sql;
@@ tableBook.sql;
@@ tableBookAuthor.sql;
@@ tableBookCategory.sql;
@@ tableBookCopy.sql;
@@ tableLoan.sql;
@@ tableFine.sql;
@@ tableInvoice.sql;
@@ tablePaymentMethod.sql;
@@ tablePayment.sql;
-- WARN: Pending testing
@@ tableMembershipCatalog.sql;
